name: Build Main Branch

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 6 * * 2"

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".Dockerfile"

  build:
    needs: list-files
        
    permissions:
      packages: write
      contents: read
      
    strategy:
      matrix:
        version: ['1.16.0']
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free disk space
        run: chmod +x ./scripts/cleanup.sh && ./scripts/cleanup.sh

      - name: Check disk space
        run: chmod +x ./scripts/check-space.sh && ./scripts/check-space.sh

      - name: get image info
        run: |
          echo "IMAGENAME=${{ matrix.paths }}" | sed 's/\.\///g' | sed 's/\.[^.]*$//' >>${GITHUB_ENV}
          sed -i "s/%VER%/${{ matrix.version }}/" ${{ matrix.paths }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.paths }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/dmptrluke/kasm-workspace-${{ env.IMAGENAME }}:${{ matrix.version }}
          cache-from: type=registry,ref=ghcr.io/dmptrluke/kasm-workspace-${{ env.IMAGENAME }}:${{ matrix.version }}
          cache-to: type=inline